services:
  mariadb:
    build: database
    container_name: mariadb
    restart: on-failure
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "health", "-phealth", "--skip-ssl"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  wordpress:
    build: wordpress
    container_name: wordpress
    restart: on-failure
    env_file: .env
    depends_on:
      mariadb:
         condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception
  
  nginx:
    build: nginx
    container_name: nginx
    restart: on-failure
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
      - adminer
    volumes:
      - wp-data:/var/www/html
  
  # ------ bonus ------

  redis:
    build: bonus/redis
    container_name: redis
    restart: on-failure
    env_file: .env
    ports:
      - "6379:6379"
    networks:
      - inception
  
  adminer:
    build: bonus/adminer
    container_name: adminer
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
         condition: service_healthy
    networks:
      - inception
    
  ftp:
    build: bonus/ftp
    container_name: ftp
    restart: on-failure
    env_file: .env
    volumes:
     - wp-data:/var/www/html
    ports: 
      - "21:21"
      - "21210-21220:21210-21220"
    networks:
     - inception

  static_page:
    build: bonus/static_page
    container_name: static_page
    restart: on-failure
    ports:
      - "1818:1818"
    networks:
     - inception

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  db-data :
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ${DATA_PATH}/data/db
  wp-data:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ${DATA_PATH}/data/wordpress
