services :
  mariadb :
    build: database
    container_name: mariadb
    restart: on-failure
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inception

  wordpress :
    build: wordpress
    container_name: wordpress
    restart: on-failure
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception
  
  nginx:
    build: nginx
    container_name : nginx
    restart: on-failure
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/ww/html
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  db-data :
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ${DATA_PATH}/data/db
  wp-data:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ${DATA_PATH}/data/wordpress
