services :
  database :
    image : database
    volume : db-data:/var/lib
    env_file : .env

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device : "/home/csenelle/data/db"