services :
  mariadb :
    build: database
    restart: on-failure
    container_name: mariadb
    env_file: .env
    volumes:
      - ${DATA_PATH}/data/db:/var/lib/mysql
    ports:
      - "3306:3306"
  wordpress :
    build: wordpress
    restart: on-failure
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    volumes:
      - ${DATA_PATH}/data/wordpress

networks:
  inception:
    driver: bridge